-- Drivers & Guide Info Masters
-- Run after admin_masters.sql (or rely on sequelize.sync for new installs)

CREATE TABLE IF NOT EXISTS `tt_drivers` (
  `id` CHAR(36) NOT NULL,
  `code` VARCHAR(50) NOT NULL,
  `full_name` VARCHAR(150) NOT NULL,
  `photo` VARCHAR(500) DEFAULT NULL,
  `license_number` VARCHAR(50) NOT NULL,
  `license_type` VARCHAR(50) DEFAULT NULL,
  `license_expiry` DATE DEFAULT NULL,
  `id_proof_type` VARCHAR(50) DEFAULT NULL,
  `id_proof_number` VARCHAR(50) DEFAULT NULL,
  `proof_document` VARCHAR(500) DEFAULT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `alternate_phone` VARCHAR(20) DEFAULT NULL,
  `email` VARCHAR(150) DEFAULT NULL,
  `address` TEXT DEFAULT NULL,
  `city` VARCHAR(100) DEFAULT NULL,
  `emergency_contact_name` VARCHAR(150) DEFAULT NULL,
  `emergency_contact_phone` VARCHAR(20) DEFAULT NULL,
  `emergency_contact_relation` VARCHAR(50) DEFAULT NULL,
  `employment_type` VARCHAR(50) DEFAULT NULL,
  `experience_years` INT DEFAULT 0,
  `joining_date` DATE DEFAULT NULL,
  `blood_group` VARCHAR(10) DEFAULT NULL,
  `vehicle_id` CHAR(36) DEFAULT NULL,
  `availability_status` VARCHAR(30) DEFAULT 'available',
  `notes` TEXT DEFAULT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_by` CHAR(36) DEFAULT NULL,
  `updated_by` CHAR(36) DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_tt_drivers_code` (`code`),
  UNIQUE KEY `uq_tt_drivers_license` (`license_number`),
  KEY `idx_tt_drivers_is_active` (`is_active`),
  KEY `idx_tt_drivers_phone` (`phone`),
  KEY `idx_tt_drivers_vehicle_id` (`vehicle_id`),
  KEY `idx_tt_drivers_availability` (`availability_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tt_driver_proofs` (
  `id` CHAR(36) NOT NULL,
  `driver_id` CHAR(36) NOT NULL,
  `proof_type` VARCHAR(50) NOT NULL,
  `proof_number` VARCHAR(50) DEFAULT NULL,
  `license_type` VARCHAR(50) DEFAULT NULL,
  `expiry_date` DATE DEFAULT NULL,
  `images` TEXT DEFAULT NULL,
  `display_order` INT DEFAULT 0,
  `notes` TEXT DEFAULT NULL,
  `created_by` CHAR(36) DEFAULT NULL,
  `updated_by` CHAR(36) DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_tt_driver_proofs_driver_id` (`driver_id`),
  KEY `idx_tt_driver_proofs_type` (`proof_type`),
  CONSTRAINT `fk_tt_driver_proofs_driver`
    FOREIGN KEY (`driver_id`) REFERENCES `tt_drivers` (`id`)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `tt_guides` (
  `id` CHAR(36) NOT NULL,
  `code` VARCHAR(50) NOT NULL,
  `full_name` VARCHAR(150) NOT NULL,
  `photo` VARCHAR(500) DEFAULT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `alternate_phone` VARCHAR(20) DEFAULT NULL,
  `whatsapp` VARCHAR(20) DEFAULT NULL,
  `email` VARCHAR(150) DEFAULT NULL,
  `address` TEXT DEFAULT NULL,
  `city` VARCHAR(100) DEFAULT NULL,
  `emergency_phone` VARCHAR(20) DEFAULT NULL,
  `languages` VARCHAR(255) DEFAULT NULL,
  `specialization` VARCHAR(255) DEFAULT NULL,
  `license_number` VARCHAR(50) DEFAULT NULL,
  `license_expiry` DATE DEFAULT NULL,
  `id_proof_type` VARCHAR(50) DEFAULT NULL,
  `id_proof_number` VARCHAR(50) DEFAULT NULL,
  `proof_document` VARCHAR(500) DEFAULT NULL,
  `experience_years` INT DEFAULT 0,
  `daily_rate` DECIMAL(12, 2) DEFAULT 0,
  `joining_date` DATE DEFAULT NULL,
  `destination_ids` TEXT DEFAULT NULL,
  `coverage_areas` VARCHAR(500) DEFAULT NULL,
  `availability_status` VARCHAR(30) DEFAULT 'available',
  `bio` TEXT DEFAULT NULL,
  `notes` TEXT DEFAULT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_by` CHAR(36) DEFAULT NULL,
  `updated_by` CHAR(36) DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_tt_guides_code` (`code`),
  KEY `idx_tt_guides_is_active` (`is_active`),
  KEY `idx_tt_guides_phone` (`phone`),
  KEY `idx_tt_guides_availability` (`availability_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
