const express = require('express');
const { authenticate } = require('../middleware/auth.middleware');

const healthRoutes = require('./health.routes');
const authRoutes = require('./auth.routes');
const publicEnquiryRoutes = require('./publicEnquiry.routes');
const publicFeedbackRoutes = require('./publicFeedback.routes');
const publicItineraryRoutes = require('./publicItinerary.routes');
const driverPortalRoutes = require('./driverPortal.routes');
const userRoutes = require('./user.routes');
const roleRoutes = require('./role.routes');
const dashboardRoutes = require('./dashboard.routes');
const leadRoutes = require('./lead.routes');
const enquiryRoutes = require('./enquiry.routes');
const followUpRoutes = require('./followUp.routes');
const masterRoutes = require('./master.routes');
const quotationRoutes = require('./quotation.routes');
const bookingRoutes = require('./booking.routes');
const invoiceRoutes = require('./invoice.routes');
const receiptRoutes = require('./receipt.routes');
const paymentRoutes = require('./payment.routes');
const expenseRoutes = require('./expense.routes');
const refundRoutes = require('./refund.routes');
const feedbackRoutes = require('./feedback.routes');
const itineraryRoutes = require('./itinerary.routes');
const reportRoutes = require('./report.routes');
const notificationRoutes = require('./notification.routes');
const auditRoutes = require('./audit.routes');
const calendarRoutes = require('./calendar.routes');
const whatsappTemplateRoutes = require('./whatsappTemplate.routes');
const loginHistoryRoutes = require('./loginHistory.routes');
const userTablePreferenceRoutes = require('./userTablePreference.routes');
const integrationRoutes = require('./integration.routes');
const whatsappInboxRoutes = require('./whatsappInbox.routes');
const wasenderWebhookRoutes = require('./wasenderWebhook.routes');

const router = express.Router();

router.use('/health', healthRoutes);
router.use('/auth', authRoutes);
router.use('/public/enquiries', publicEnquiryRoutes);
router.use('/public/feedback', publicFeedbackRoutes);
router.use('/public/itineraries', publicItineraryRoutes);
router.use('/public/wasender', wasenderWebhookRoutes);
router.use('/driver', driverPortalRoutes);

router.use(authenticate);

router.use('/me/table-preferences', userTablePreferenceRoutes);
router.use('/users', userRoutes);
router.use('/roles', roleRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/leads', leadRoutes);
router.use('/enquiries', enquiryRoutes);
router.use('/follow-ups', followUpRoutes);
router.use('/masters', masterRoutes);
router.use('/quotations', quotationRoutes);
router.use('/bookings', bookingRoutes);
router.use('/invoices', invoiceRoutes);
router.use('/receipts', receiptRoutes);
router.use('/payments', paymentRoutes);
router.use('/expenses', expenseRoutes);
router.use('/refunds', refundRoutes);
router.use('/feedback', feedbackRoutes);
router.use('/itineraries', itineraryRoutes);
router.use('/reports', reportRoutes);
router.use('/notifications', notificationRoutes);
router.use('/audit-logs', auditRoutes);
router.use('/calendar', calendarRoutes);
router.use('/whatsapp-templates', whatsappTemplateRoutes);
router.use('/whatsapp-inbox', whatsappInboxRoutes);
router.use('/integrations', integrationRoutes);
router.use('/login-history', loginHistoryRoutes);

module.exports = router;
