/*
SQLyog Community v13.3.1 (64 bit)
MySQL - 10.4.32-MariaDB 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

create table `lead_status_whatsapp_templates` (
	`id` char (108),
	`lead_status_id` char (108),
	`template_name` varchar (450),
	`template_content` text ,
	`template_id` varchar (300),
	`language_code` varchar (60),
	`include_itinerary` tinyint (1),
	`header_media_url` varchar (1500),
	`message_notes` text ,
	`is_active` tinyint (1),
	`created_by` char (108),
	`updated_by` char (108),
	`created_at` datetime ,
	`updated_at` datetime ,
	`deleted_at` datetime 
); 
insert into `lead_status_whatsapp_templates` (`id`, `lead_status_id`, `template_name`, `template_content`, `template_id`, `language_code`, `include_itinerary`, `header_media_url`, `message_notes`, `is_active`, `created_by`, `updated_by`, `created_at`, `updated_at`, `deleted_at`) values('0a472dc6-4205-40f1-8263-249f2f3ab2fa',NULL,'Vehicle_driver_assigned','Dear {{customer_name}}, ?\n\nYour trip vehicle and driver have been successfully assigned. ?\n\nTrip Details:\n? Trip Date: {{trip_date}}\n? Pickup Id: {{trip_id}}\n? Destination: {{trip_to_destination}}\n\nVehicle Details:\n? Vehicle No: {{vehicle_number}}\n? Vehicle Type: {{vehicle_type}}\n\nDriver Details:\n?‍✈️ Driver Name: {{driver_name}}\n? Driver Contact: {{driver_mobile}}\n\nPlease contact the driver directly if required.\n\nHave a safe and comfortable journey! ?\n\nThank you for choosing {{company_name}} ?',NULL,'en_US','0',NULL,NULL,'1',NULL,NULL,'2026-08-28 17:45:35','2026-08-28 17:45:35',NULL);
insert into `lead_status_whatsapp_templates` (`id`, `lead_status_id`, `template_name`, `template_content`, `template_id`, `language_code`, `include_itinerary`, `header_media_url`, `message_notes`, `is_active`, `created_by`, `updated_by`, `created_at`, `updated_at`, `deleted_at`) values('3295f3a2-547c-41a3-a43f-93b62dd03fb7','70d2dfb2-20c8-48e1-8c4e-2b4f87f6bcdb','Assign Enquiry','Dear {{Customer}}\n\nYour Enquiry has been Verified and Assigned.\n\nYour Trip Id is {{trip_id}}\n\nThanks for reaching Pollachi Tours & Travels',NULL,'en_US','0',NULL,NULL,'1',NULL,NULL,'2026-08-28 17:45:35','2026-08-28 17:45:35',NULL);
insert into `lead_status_whatsapp_templates` (`id`, `lead_status_id`, `template_name`, `template_content`, `template_id`, `language_code`, `include_itinerary`, `header_media_url`, `message_notes`, `is_active`, `created_by`, `updated_by`, `created_at`, `updated_at`, `deleted_at`) values('63f5ea5a-3974-4acc-9fd3-b45bd7d5ecde',NULL,'driver_login_credentials','? *Driver Login & Trip Details*\n\nDear *{{driver_name}}*,\n\nYour driver login account has been created successfully.\n\n? *Username:* {{username}}\n? *Password:* {{password}}\n? *Login Link:* {{login_link}}\n\n? *Assigned Trip Details:*\n• *Trip ID:* {{trip_id}}\n• *Customer Name:* {{customer_name}}\n• *Trip Date:* {{trip_date}}\n• *Pickup Location:* {{pickup_location}}\n• *Destination:* {{destination}}\n• *Vehicle No:* {{vehicle_number}}\n\nPlease log in using the above credentials and check your complete trip details.\n\n⚠️ Please keep your username and password confidential.\n\nThank you,\n*{{company_name}}*',NULL,'en_US','0',NULL,NULL,'1',NULL,NULL,'2026-08-28 17:45:35','2026-08-28 17:45:35',NULL);
insert into `lead_status_whatsapp_templates` (`id`, `lead_status_id`, `template_name`, `template_content`, `template_id`, `language_code`, `include_itinerary`, `header_media_url`, `message_notes`, `is_active`, `created_by`, `updated_by`, `created_at`, `updated_at`, `deleted_at`) values('6d4d40a4-64c4-4b06-b989-9a6e6181d633','2519c449-7ebb-4fe3-886c-969a73ed2da6','Booking Confirmed','Dear {{Customer}},\n\nYour Booking has been Confirmed.\n\nYour trip Id is {{trip_id}}\n\nThanks for reaching Pollachi Tours & Travels',NULL,'en_US','0',NULL,NULL,'1',NULL,NULL,'2026-08-28 17:45:35','2026-08-28 17:45:35',NULL);
insert into `lead_status_whatsapp_templates` (`id`, `lead_status_id`, `template_name`, `template_content`, `template_id`, `language_code`, `include_itinerary`, `header_media_url`, `message_notes`, `is_active`, `created_by`, `updated_by`, `created_at`, `updated_at`, `deleted_at`) values('92e33ecb-1577-4811-8123-36dcd417268b',NULL,'payment_Receipt','Dear {{customer_name}}, ?\n\nThank you for your payment. ?\n\nYour Payment Receipt has been generated successfully.\n\nPayment Details:\n? Receipt No: {{receipt_number}}\n? Payment Date: {{payment_date}}\n? Amount Paid: ₹{{paid_amount}}\n? Payment Mode: {{payment_mode}}\n? Trip Id: {{trip_id}}\n\nPlease find your payment receipt attached to this message. ?\n\nThank you for choosing {{company_name}} ?\nWe look forward to serving you!\n\n{{company_name}}\n? {{company_mobile}}',NULL,'en_US','0',NULL,NULL,'1',NULL,NULL,'2026-08-28 17:45:35','2026-08-28 17:45:35',NULL);
insert into `lead_status_whatsapp_templates` (`id`, `lead_status_id`, `template_name`, `template_content`, `template_id`, `language_code`, `include_itinerary`, `header_media_url`, `message_notes`, `is_active`, `created_by`, `updated_by`, `created_at`, `updated_at`, `deleted_at`) values('9cff0dab-12ca-42fc-87d8-16f36a1f2b1a','34bbf414-bef5-455c-8372-b54a30f9074c','Itinerary Preparation','Dear {{Customer}}\n\nGreetings from {{company_name}}!\n\nWe are happy to share your travel itinerary for your upcoming trip.\n\nDestination: {{destination}}\nTravel Dates: {{travel_dates}}\nTravellers: {{adults}} Adult(s), {{children}} Child(ren)\n\nYour detailed itinerary includes the day-wise travel plan, destinations, activities, and other trip details.\n\nKindly review the itinerary and let us know if you need any changes or customization. We will be happy to assist you.\n\nThank you for choosing {{company_name}}!\n\nContact us: {{company_phone}}',NULL,'en_US','0',NULL,NULL,'1',NULL,NULL,'2026-08-28 17:45:35','2026-08-28 17:45:35',NULL);
insert into `lead_status_whatsapp_templates` (`id`, `lead_status_id`, `template_name`, `template_content`, `template_id`, `language_code`, `include_itinerary`, `header_media_url`, `message_notes`, `is_active`, `created_by`, `updated_by`, `created_at`, `updated_at`, `deleted_at`) values('a8592415-2b16-44b2-8c29-ed5eab879689',NULL,'Trip_completed','? *Trip Completed Successfully*\n\nDear *{{Customer Name}}*,\n\nWe are pleased to inform you that your trip has been completed successfully.\n\n? *Trip Details:*\n• *Trip ID:* {{TRIP ID}}\n• *Trip Date:* {{TRIP DATE}}\n• *Pickup:* {{PICKUP LOCATION}}\n• *Destination:* {{DESTINATION}}\n• *Vehicle No:* {{VEHICLE NUMBER}}\n\n? *Invoice Details:*\n• *Invoice No:* {{INVOICE NUMBER}}\n• *Invoice Date:* {{INVOICE DATE}}\n• *Total Amount:* ₹ {{TOTAL AMOUNT}}\n• *Paid Amount:* ₹ {{PAID AMOUNT}}\n• *Balance Amount:* ₹ {{BALANCE AMOUNT}}\n\n? Your invoice has been shared with this message for your reference.\n\nThank you for choosing *{{Company Name}}*. We look forward to serving you again! ?',NULL,'en_US','0',NULL,NULL,'1',NULL,NULL,'2026-08-28 17:45:35','2026-08-28 17:45:35',NULL);
insert into `lead_status_whatsapp_templates` (`id`, `lead_status_id`, `template_name`, `template_content`, `template_id`, `language_code`, `include_itinerary`, `header_media_url`, `message_notes`, `is_active`, `created_by`, `updated_by`, `created_at`, `updated_at`, `deleted_at`) values('f38924bf-2eca-4283-8fb3-c34149b7cee2',NULL,'customer_feedback','⭐ *We Value Your Feedback*\n\nDear *{{Customer Name}}*,\n\nThank you for choosing *{{Company Name}}* for your recent trip. ?\n\nWe hope you had a safe and pleasant journey with us. Your feedback is very valuable and helps us improve our services.\n\nPlease take a moment to share your experience by clicking the link below:\n\n? *Feedback Link:* {{FEEDBACK LINK}}\n\nThank you for your valuable time and feedback. We look forward to serving you again! ?✨\n\n*{{Company Name}}*',NULL,'en_US','0',NULL,NULL,'1',NULL,NULL,'2026-08-28 17:45:35','2026-08-28 17:45:35',NULL);
