import {
  DashboardOutlined,
  PeopleOutlined,
  SecurityOutlined,
  BusinessOutlined,
  HotelOutlined,
  DirectionsCarOutlined,
  AirlineSeatReclineNormalOutlined,
  TourOutlined,
  LocalShippingOutlined,
  LabelOutlined,
  CampaignOutlined,
  ContactMailOutlined,
  PhoneCallbackOutlined,
  MapOutlined,
  RequestQuoteOutlined,
  ReceiptLongOutlined,
  PaymentsOutlined,
  AccountBalanceWalletOutlined,
  ReviewsOutlined,
  CalendarMonthOutlined,
  SettingsOutlined,
  HistoryOutlined,
  LoginOutlined,
  PublicOutlined,
  CreditCardOutlined,
  WbSunnyOutlined,
  CategoryOutlined,
  AccountTreeOutlined,
  BadgeOutlined,
  DescriptionOutlined,
  PlaylistAddCheckOutlined,
  AssessmentOutlined,
  AccountBalanceOutlined,
  GroupsOutlined,
  FactCheckOutlined,
} from '@mui/icons-material';
import { PERMISSIONS } from '../utils/permissions';

export const menuConfig = [
  {
    id: 'dashboard',
    title: 'Dashboard',
    path: '/dashboard',
    icon: DashboardOutlined,
    permission: PERMISSIONS.DASHBOARD_VIEW,
  },
  {
    id: 'enquiries',
    title: 'Enquiries',
    path: '/enquiry',
    icon: ContactMailOutlined,
    permission: PERMISSIONS.ENQUIRIES_VIEW,
  },
  {
    id: 'followups',
    title: 'Follow-ups',
    path: '/follow-ups',
    icon: PhoneCallbackOutlined,
    permission: PERMISSIONS.FOLLOW_UPS_VIEW,
  },
  {
    id: 'itinerary',
    title: 'Itineraries',
    path: '/itineraries',
    icon: MapOutlined,
    permission: PERMISSIONS.ITINERARIES_VIEW,
  },
  {
    id: 'quotations',
    title: 'Quotations',
    path: '/quotations',
    icon: RequestQuoteOutlined,
    permission: PERMISSIONS.QUOTATIONS_VIEW,
  },
  {
    id: 'calendar',
    title: 'Calendar',
    path: '/calendar',
    icon: CalendarMonthOutlined,
    permission: PERMISSIONS.CALENDAR_VIEW,
  },
  {
    id: 'invoices',
    title: 'Invoices',
    path: '/invoices',
    icon: ReceiptLongOutlined,
    permission: PERMISSIONS.INVOICES_VIEW,
  },
  {
    id: 'receipts',
    title: 'Receipts',
    path: '/receipts',
    icon: PaymentsOutlined,
    permission: PERMISSIONS.RECEIPTS_VIEW,
  },
  {
    id: 'feedback',
    title: 'Feedback',
    path: '/feedback',
    icon: ReviewsOutlined,
    permission: PERMISSIONS.FEEDBACK_VIEW,
  },
  {
    id: 'expenses',
    title: 'Expenses',
    path: '/expenses',
    icon: AccountBalanceWalletOutlined,
    permission: PERMISSIONS.EXPENSES_VIEW,
  },
  {
    id: 'reports',
    title: 'Reports',
    icon: AssessmentOutlined,
    permission: PERMISSIONS.REPORTS_VIEW,
    children: [
      {
        id: 'report-profit-loss',
        title: 'Profit and Loss',
        path: '/reports/profit-loss',
        icon: AccountBalanceOutlined,
        permission: PERMISSIONS.REPORTS_VIEW,
      },
      {
        id: 'report-enquiries',
        title: 'Enquiry Report',
        path: '/reports/enquiries',
        icon: ContactMailOutlined,
        permission: PERMISSIONS.REPORTS_VIEW,
      },
      {
        id: 'report-expenses',
        title: 'Expenses Report',
        path: '/reports/expenses',
        icon: ReceiptLongOutlined,
        permission: PERMISSIONS.REPORTS_VIEW,
      },
      {
        id: 'report-customers',
        title: 'Customer Report',
        path: '/reports/customers',
        icon: GroupsOutlined,
        permission: PERMISSIONS.REPORTS_VIEW,
      },
      {
        id: 'report-vehicles',
        title: 'Vehicle Report',
        path: '/reports/vehicles',
        icon: DirectionsCarOutlined,
        permission: PERMISSIONS.REPORTS_VIEW,
      },
      {
        id: 'report-drivers',
        title: 'Drivers Report',
        path: '/reports/drivers',
        icon: AirlineSeatReclineNormalOutlined,
        permission: PERMISSIONS.REPORTS_VIEW,
      },
      {
        id: 'report-followups',
        title: 'User Follow-ups',
        path: '/reports/follow-ups',
        icon: PhoneCallbackOutlined,
        permission: PERMISSIONS.REPORTS_VIEW,
      },
      {
        id: 'report-attendance',
        title: 'User Attendance',
        path: '/reports/attendance',
        icon: FactCheckOutlined,
        permission: PERMISSIONS.REPORTS_VIEW,
      },
    ],
  },
  {
    id: 'masters',
    title: 'Masters',
    icon: BusinessOutlined,
    children: [
      {
        id: 'branches',
        title: 'Branches',
        path: '/masters/branches',
        icon: BusinessOutlined,
        permission: PERMISSIONS.BRANCHES_VIEW,
      },
      {
        id: 'hotels',
        title: 'Hotels',
        path: '/masters/hotels',
        icon: HotelOutlined,
        permission: PERMISSIONS.HOTELS_VIEW,
      },
      {
        id: 'vehicles',
        title: 'Vehicles',
        path: '/masters/vehicles',
        icon: DirectionsCarOutlined,
        permission: PERMISSIONS.VEHICLES_VIEW,
      },
      {
        id: 'drivers',
        title: 'Drivers',
        path: '/masters/drivers',
        icon: AirlineSeatReclineNormalOutlined,
        permission: PERMISSIONS.DRIVERS_VIEW,
      },
      {
        id: 'guides',
        title: 'Guide Info',
        path: '/masters/guides',
        icon: TourOutlined,
        permission: PERMISSIONS.GUIDES_VIEW,
      },
      {
        id: 'suppliers',
        title: 'Vendor',
        path: '/masters/suppliers',
        icon: LocalShippingOutlined,
        permission: PERMISSIONS.SUPPLIERS_VIEW,
      },
      {
        id: 'lead-statuses',
        title: 'Lead Status',
        path: '/masters/lead-statuses',
        icon: LabelOutlined,
        permission: PERMISSIONS.LEAD_STATUSES_VIEW,
      },
      {
        id: 'lead-source-types',
        title: 'Lead Source Type',
        path: '/masters/lead-source-types',
        icon: CampaignOutlined,
        permission: PERMISSIONS.LEAD_SOURCE_TYPES_VIEW,
      },
      {
        id: 'package-terms',
        title: 'Package Terms',
        path: '/masters/package-terms',
        icon: DescriptionOutlined,
        permission: PERMISSIONS.PACKAGE_TERMS_VIEW,
      },
      {
        id: 'inclusion-exclusions',
        title: 'Inclusions & Exclusions',
        path: '/masters/inclusion-exclusions',
        icon: PlaylistAddCheckOutlined,
        permission: PERMISSIONS.INCLUSION_EXCLUSIONS_VIEW,
      },
      {
        id: 'countries',
        title: 'Country',
        path: '/masters/countries',
        icon: PublicOutlined,
        permission: PERMISSIONS.COUNTRIES_VIEW,
      },
      {
        id: 'payment-modes',
        title: 'Payment Mode',
        path: '/masters/payment-modes',
        icon: CreditCardOutlined,
        permission: PERMISSIONS.PAYMENT_MODES_VIEW,
      },
      {
        id: 'season-pricing',
        title: 'Season Pricing',
        path: '/masters/season-pricing',
        icon: WbSunnyOutlined,
        permission: PERMISSIONS.SEASON_PRICING_VIEW,
      },
      {
        id: 'expenses-types',
        title: 'Expenses Type',
        path: '/masters/expenses-types',
        icon: CategoryOutlined,
        permission: PERMISSIONS.EXPENSES_TYPES_VIEW,
      },
    ],
  },
  {
    id: 'admin',
    title: 'Administration',
    icon: SecurityOutlined,
    children: [
      {
        id: 'users',
        title: 'Users',
        path: '/users',
        icon: PeopleOutlined,
        permission: PERMISSIONS.USERS_VIEW,
      },
      {
        id: 'roles',
        title: 'Roles',
        path: '/roles',
        icon: SecurityOutlined,
        permission: PERMISSIONS.ROLES_VIEW,
      },
      {
        id: 'departments',
        title: 'Departments',
        path: '/masters/departments',
        icon: AccountTreeOutlined,
        permission: PERMISSIONS.DEPARTMENTS_VIEW,
      },
      {
        id: 'designations',
        title: 'Designation',
        path: '/masters/designations',
        icon: BadgeOutlined,
        permission: PERMISSIONS.DESIGNATIONS_VIEW,
      },
      {
        id: 'audit',
        title: 'Audit Logs',
        path: '/audit-logs',
        icon: HistoryOutlined,
        permission: PERMISSIONS.AUDIT_LOGS_VIEW,
      },
      {
        id: 'login-history',
        title: 'Login History',
        path: '/login-history',
        icon: LoginOutlined,
        permission: PERMISSIONS.LOGIN_HISTORY_VIEW,
      },
      {
        id: 'settings',
        title: 'Settings',
        path: '/settings',
        icon: SettingsOutlined,
        permission: PERMISSIONS.SETTINGS_VIEW,
      },
    ],
  },
];

export default menuConfig;
